### ISSUE TITLE
Another app is currently holding the xtables lock. perhaps you want to use the -w option?

### ISSUE THREAD

**Issue by caltuntas** [newsnowlabs/docker-ingress-routing-daemon#29]
While struggling to find a solution for the well-known Docker Swarm ingress problem, I came across this project. Thank you for releasing it to the public!

I have a simple cluster consisting of 3 nodes (1 manager and 2 workers, Ubuntu 20.04.5 LTS). We have around 5 ingress services, and the VIP/Cluster IP is configured using 'keepalived'. All the ingress services are accessed from the 3 node IPs plus the VIP. If I'm not mistaken, all the nodes are considered 'load balancer' nodes.

After installing 'DIRD' on all the nodes, I attempted to access all services from the aforementioned IP addresses. However, the results were inconsistent. Sometimes a service was only accessible from a single IP, sometimes two, and sometimes all.

Upon inspecting the journal logs, I noticed multiple instances of the error message 'Another app is currently holding the xtables lock'. This error prevented 'DIRD' from modifying the iptables.

To resolve this issue, I replaced 'iptables -t' with 'iptables -w -t' using the command 'sed -i 's/iptables -t/iptables -w -t/g' /usr/local/bin/docker-ingress-routing-daemon'. It appears that adding the '-w' flag resolved the problem in my case, although I am unsure if it may cause issues elsewhere.

**Comment by struanb** [comment]
Hi @caltuntas. Many thanks for trying DIRD and for raising this issue and proposing this solution. 

We'll look at this.

**Comment by struanb** [comment]
@caltuntas Finally I have got round to adding support for iptables `--wait` and `--wait-seconds <n>` options:

https://github.com/newsnowlabs/docker-ingress-routing-daemon/tree/iptables-wait

**Comment by struanb** [comment]
This branch is now merged into main. Thanks @caltuntas for raising this issue, which I will now close.
