### ISSUE TITLE
Feature Request: Whitelist Services/Ports

### ISSUE THREAD

**Issue by ztimson** [newsnowlabs/docker-ingress-routing-daemon#33]
Hey I have been using `dird` for awhile and it works great for websites; however it can cause issues for game servers & other complex services.

I can currently blacklist these services/ports but it's quite a hassel when you have multiple servers and services that are being updated. 

I really only need IP's corrected for my reverse proxy that all my web services run through. Can whitelisting be added as arguments? Using a whitelist would save me form having to check & reconfigure `dird` when I run into a routing issue with a new service.

Thanks!

**Comment by struanb** [comment]
Hi @ztimson Thanks for using DIRD. For some reason we didn't receive notification, so apologies for the delayed response.

Have you tried using any of these options?

```
--services <services>  - service names to disable masquerading for
             --tcp-ports <ports>  - TCP ports to disable masquerading for
             --udp-ports <ports>  - UDP ports to disable masquerading for
```

"Disable masquerading for" means "enable routing for", so these should be the whitelist options that you want.

**Comment by ztimson** [comment]
@struanb No problem at all, using the flags provided did indeed work, thank you!
The language defintely confused me.

**Comment by struanb** [comment]
I've updated the language in the [README](https://github.com/newsnowlabs/docker-ingress-routing-daemon#readme), which I hope you agree is clearer about the whitelisting options, and will now close this issue.
